language: rust
matrix:
  include:
    # Stable channel.
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu

script:
  - cargo install clippy
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo clippy --verbose --all
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry