language: rust
matrix:
  include:
    # Stable channel.
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
jobs:
  include:
    - stage: Build
      script: 
        - cargo build --verbose --all
    - stage: Lint
      before_script: 
        - rustup component add clippy
      script:
        - cargo clippy --verbose --all
    - stage: Tests
      name: Unit Tests
      script: 
        - cargo test --verbose --all
    - name: End to End Tests
      before_script: 
        - cargo install --path ichop --force
      script:
        - ./milestones/test.sh 
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry